Repository haqq-network/haqq-wallet, pull requests merged in 2022-12, with the labels that each got.

#476 feat(Staking): home staking screen
  assets/animations/get-reward-light.json
  assets/animations/stake-light-0-20.json
  assets/animations/stake-light-100.json
  assets/animations/stake-light-20-100.json
  src/components/home-staking/home-staking.tsx
  src/components/home-staking/staking-active.tsx
  src/components/home-staking/staking-empty.tsx
  src/components/ui/index.ts
  src/components/ui/text-sum.tsx
  src/hooks/index.ts
  src/hooks/use-wallets.ts
  src/i18n.ts
  src/models/staking-metadata.ts
  src/screens/home-staking.tsx
Labels: flow

#552 chore: check labels
  .github/workflows/validate-label.yml
Labels: no-qa

#539 refactor(settingsTest): code
  src/components/settings-test/index.tsx
  src/components/settings-test/settings-test.tsx
  src/i18n.ts
  src/screens/settings-test.tsx
Labels: no-qa

#538 refactor(SettingsLanguage): code
  src/components/settings-language.tsx
  src/screens/settings-language.tsx
Labels: no-qa

#560 chore: distribute iOS app
  .github/workflows/distribute-ios-build.yml
  .github/workflows/distribute-ios.yml
  .github/workflows/distribute.yml
  .github/workflows/release.yml
Labels: no-qa

#570 feat: change finish to proceed
  src/components/finish.tsx
  src/i18n.ts
  src/screens/ledger-finish.tsx
  src/screens/onboarding-finish.tsx
Labels: need-qa

#541 refactor(Welcome): code
  src/components/welcome.tsx
  src/screens/welcome.tsx
Labels: no-qa

#546 refactor(LadgerVerify): code
  src/components/ledger-verify/ledger-verify.tsx
  src/i18n.ts
  src/screens/ledger-verify.tsx
Labels: no-qa

#540 refactor(LedgerStoreWallet): code
  src/i18n.ts
  src/screens/ledger-store-wallet.tsx
Labels: no-qa

#532 refactor(SettingsAddressBook): code
  src/components/list-contact.tsx
  src/components/settings-address-book.tsx
  src/components/ui/text-field.tsx
  src/hocs/with-actions-contact-item.tsx
  src/i18n.ts
  src/screens/settings-address-book.tsx
Labels: no-qa

#555 refactor(backupWarning): code & design
  assets/animations/recover-animation-dark.json
  src/i18n.ts
  src/screens/backup-warning.tsx
Labels: refactor, no-qa

#545 refactor(SettingsSecurity): code
  src/components/pin.tsx
  src/components/settings-security/index.tsx
  src/components/settings-security/settings-security.tsx
  src/i18n.ts
  src/screens/settings-security.tsx
Labels: refactor, no-qa

#556 refactor(SinginAgreement): code
  src/components/restore-agreement/restore-agreement.tsx
  src/screens/signin-agreement.tsx
Labels: refactor, no-qa

#566 refactor(LedgerBluetooth): code
  src/components/ledger-bluetooth/ledger-bluetooth.tsx
  src/screens/ledger-bluetooth.tsx
Labels: refactor, no-qa

#572 fix(SettingsTheme): fix paddings
  src/components/home-settings/home-settings.tsx
  src/components/home-settings/settings-button.tsx
  src/components/settings-providers/settings-providers-row.tsx
  src/components/settings-theme/settings-theme.tsx
  src/components/settings-theme/theme-button.tsx
  src/components/ui/data-content.tsx
  src/components/ui/menu-navigation-button.tsx
Labels: need-qa

#530 refactor(SettingsAccounts): code
  src/components/settings-accounts.tsx
  src/components/ui/card-small.tsx
  src/components/wallet-row.tsx
  src/i18n.ts
  src/screens/settings-accounts.tsx
Labels: refactor, no-qa

#565 refactor(LedgerAgreement): code
  src/components/ledger-agreement/ledger-agreement.tsx
  src/screens/ledger-agreement.tsx
Labels: refactor, no-qa

#554 refactor(SettingsSecurityPin): code
  src/components/settings-security-pin/index.tsx
  src/components/settings-security-pin/settings-security-pin.tsx
  src/i18n.ts
  src/screens/settings-security-pin.tsx
Labels: refactor, no-qa

#542 refactor(TransactionSumAddress): code
  src/components/list-contact.tsx
  src/components/swipeable-button-list.tsx
  src/components/transaction-address.tsx
  src/components/ui/spacer.tsx
  src/components/ui/swipeable-button.tsx
  src/components/ui/swipeable-row.tsx
  src/screens/transaction-sum-address.tsx
Labels: refactor, no-qa

#537 refactor(SettingsFaq): code
  src/i18n.ts
  src/screens/settings-contact-edit.tsx
  src/screens/settings-faq.tsx
Labels: refactor, no-qa

#543 refactor(TransactionLedger): code
  src/components/transaction-ledger/transaction-ledger.tsx
  src/screens/transaction-ledger.tsx
Labels: refactor, no-qa

#580 refactor(Ledger): code
  src/i18n.ts
  src/screens/ledger.tsx
Labels: refactor, no-qa

#512 refactor(SettingsAbout): code
  android/app/src/main/res/drawable-hdpi/discord.png
  android/app/src/main/res/drawable-mdpi/discord.png
  android/app/src/main/res/drawable-xhdpi/discord.png
  android/app/src/main/res/drawable-xxhdpi/discord.png
  android/app/src/main/res/drawable-xxxhdpi/discord.png
  ios/haqq/Images.xcassets/discord.imageset/Contents.json
  ios/haqq/Images.xcassets/discord.imageset/discord.svg
  src/components/settings-about-button.tsx
  src/components/settings-about.tsx
  src/components/ui/icon.tsx
  src/i18n.ts
  src/screens/settings-about.tsx
Labels: refactor, no-qa

#551 feat: push notifications
  .env.example
  .github/workflows/distribute.yml
  .gitignore
  android/app/build.gradle
  android/app/google-services.json
  android/build.gradle
  index.js
  ios/GoogleService-Info.plist
  ios/Podfile
  ios/Podfile.lock
  ios/haqq.xcodeproj/project.pbxproj
  ios/haqq/AppDelegate.mm
  ios/haqq/GoogleService-Info.plist
  ios/haqq/Info.plist
  ios/haqq/haqq.entitlements
  package.json
  src/contexts/app.ts
  src/env.d.ts
  src/events.ts
  src/models/user.ts
  src/models/wallet.ts
  src/screens/settings-test.tsx
  src/services/push-notifications.ts
  yarn.lock
Labels: need-qa

#568 refactor(LedgerScan): code
  src/components/ledger-scan/ledger-scan-empty.tsx
  src/components/ledger-scan/ledger-scan-header.tsx
  src/components/ledger-scan/ledger-scan-row.tsx
  src/components/ledger-scan/ledger-scan.tsx
  src/i18n.ts
  src/screens/ledger-scan.tsx
Labels: refactor, no-qa

#581 refactor(OnboardingBiometry): code
  src/components/onboarding-biometry/index.tsx
  src/components/onboarding-biometry/onboarding-biometry.tsx
  src/i18n.ts
  src/screens/onboarding-biometry.tsx
Labels: refactor, no-qa

#584 refactor(OnboardingSetupPin): code
  src/components/onboardinng-setup-pin/index.tsx
  src/components/onboardinng-setup-pin/onboarding-setup-pin.tsx
  src/i18n.ts
  src/screens/onboarding-setup-pin.tsx
Labels: refactor, no-qa

#557 refactor(SinginStoreWallet): code
  src/i18n.ts
  src/screens/signin-store-wallet.tsx
Labels: refactor, no-qa

#567 refactor(LedgerFinish): code
  src/components/finish.tsx
  src/i18n.ts
  src/screens/ledger-finish.tsx
Labels: refactor, no-qa

#564 refactor(LedgerAccounts): code
  src/components/ledger-accounts/index.ts
  src/components/ledger-accounts/ledger-accounts-empty.tsx
  src/components/ledger-accounts/ledger-accounts-row.tsx
  src/components/ledger-accounts/ledger-accounts.tsx
  src/i18n.ts
  src/screens/ledger-accounts.tsx
  src/screens/ledger.tsx
Labels: refactor, no-qa

#528 refactor(SettingsAccountStyle): code
  src/components/settings-account-style.tsx
  src/components/ui/segmented-control.tsx
  src/i18n.ts
  src/screens/settings-account-style.tsx
Labels: refactor, no-qa

#585 refactor(HomeFeed): code
  src/components/carousel-item.tsx
  src/components/home-feed.tsx
  src/components/transaction-empty.tsx
  src/components/transaction-row.tsx
  src/components/transactions/date.tsx
  src/components/transactions/receive.tsx
  src/components/transactions/send.tsx
  src/components/ui/data-content.tsx
  src/components/wallet-card.tsx
  src/components/wallet-create.tsx
  src/components/wallets.tsx
  src/i18n.ts
  src/models/transaction.ts
  src/screens/home-feed.tsx
Labels: refactor, no-qa

#596 refactor(transactionAddress): code
  src/components/transaction-address.tsx
  src/i18n.ts
  src/screens/transaction-address.tsx
Labels: refactor, no-qa

#588 feat(ProviderForm): add provider from deep link
  package.json
  src/app.tsx
  src/components/settings-provider-edit/settings-provider-edit.tsx
  src/events.ts
  src/hooks/use-user.ts
  src/models/provider.ts
  src/navigator.ts
  src/screens/home-settings.tsx
  src/screens/settings-provider-edit.tsx
  src/types.ts
  yarn.lock
Labels: need-qa

#601 refactor(TransactionContactEdit): code
  src/screens/transaction-contact-edit.tsx
Labels: refactor, no-qa

#599 refactor(SigninStoreWallet): code
  src/i18n.ts
  src/screens/signin-store-wallet.tsx
Labels: refactor, no-qa

#590 refactor(CreateScreen): imports
  src/components/backup-warning/backup-warning.tsx
  src/components/backup-warning/index.tsx
  src/screens/backup-warning.tsx
  src/screens/backup.tsx
  src/screens/create.tsx
  src/screens/signup-store-wallet.tsx
  src/screens/signup.tsx
Labels: refactor, no-qa

#595 refactor(transactionAccounts): code
  src/components/transaction-account.tsx
  src/components/ui/card-small.tsx
  src/components/ui/data-content.tsx
  src/components/ui/menu-navigation-button.tsx
  src/i18n.ts
  src/screens/transaction-account.tsx
Labels: refactor, no-qa

#600 refactor(TransactionConfirmation): code
  src/components/transaction-confirmation/index.tsx
  src/components/transaction-confirmation/transaction-confirmation.tsx
  src/i18n.ts
  src/screens/transaction-confirmation.tsx
Labels: refactor, no-qa

#563 refactor(SigninRestoreWallet): code
  src/components/singin-restore-wallet/index.tsx
  src/components/singin-restore-wallet/signin-restore-wallet.tsx
  src/i18n.ts
  src/screens/signin-restore-wallet.tsx
Labels: refactor, no-qa

#591 refactor(signin): imports
  src/i18n.ts
  src/screens/signin.tsx
Labels: refactor, no-qa

#594 refactor(Signup): code
  src/i18n.ts
  src/screens/signup.tsx
Labels: refactor, no-qa

#592 fix: i18n
  src/i18n.ts
Labels: refactor, no-qa

#577 refactor(SettingsProvider): code
  src/components/settings-providers/settings-providers-row.tsx
  src/components/settings-providers/settings-providers.tsx
  src/screens/settings-providers.tsx
Labels: refactor, no-qa

#597 refactor(TransactionDetail): code
  src/components/transaction-detail.tsx
  src/components/ui/data-content-splitted.tsx
  src/i18n.ts
  src/screens/transaction-detail.tsx
Labels: refactor, no-qa

#603 refactor(transaction): code (#414)
  src/i18n.ts
  src/screens/transaction.tsx
Labels: refactor, no-qa

#578 refactor(OnboardingRepeatPin): code
  .eslintignore
  src/components/onboarding-repeat-pin.tsx
  src/i18n.ts
  src/screens/onboarding-repeat-pin.tsx
Labels: refactor, no-qa

#593 refactor(signupAgreement): code
  src/components/create-agreement/create-agreement.tsx
  src/screens/signup-agreement.tsx
Labels: refactor, no-qa

#602 refactor(TransactionFinish): code
  src/components/transaction-finish.tsx
  src/i18n.ts
  src/screens/transaction-finish.tsx
  src/utils.ts
Labels: refactor, no-qa

#606 refactor(BottomSheet): clean code
  src/components/address-row.tsx
  src/components/bottom-sheet.tsx
  src/components/home-staking/staking-active.tsx
  src/components/ledger-agreement/ledger-agreement.tsx
  src/components/ledger-bluetooth/ledger-bluetooth.tsx
  src/components/modals/error-account-added.tsx
  src/components/modals/error-create-account.tsx
  src/components/modals/no-internet.tsx
  src/components/pin/pin.tsx
  src/components/restore-agreement/restore-agreement.tsx
  src/components/settings-about-button.tsx
  src/components/settings-account-style.tsx
  src/components/settings-contact-edit.tsx
  src/components/staking-info/markdown.tsx
  src/components/swipeable-button-list.tsx
  src/components/transaction-detail.tsx
  src/components/transactions/receive.tsx
  src/components/transactions/send.tsx
  src/components/ui/custom-header/header-button.tsx
  src/components/ui/data-content-splitted.tsx
  src/components/ui/data-content.tsx
  src/components/ui/index.ts
  src/components/ui/sum-block.tsx
  src/helpers/index.ts
  src/i18n.ts
  src/screens/popup-backup-notification.tsx
  src/screens/settings-account-style.tsx
  src/variables.ts
Labels: no-qa

#608 fix(Welcome): fix buttons size
  src/components/ui/icon.tsx
  src/components/welcome.tsx
Labels: need-qa

#609 refactor(Notifications): change messages limit
  src/components/notification-message.tsx
  src/components/notifications.tsx
Labels: need-qa

#613 fix(Icon): try to fix icon name
  index.js
  ios/haqq/Images.xcassets/check.imageset/Check.svg
  ios/haqq/Images.xcassets/check.imageset/Contents.json
  src/components/settings-address-book-edit.tsx
Labels: need-qa

#614 feat(TransactionConfirmation): show aISLM and refactor
  src/components/transaction-confirmation/transaction-confirmation.tsx
  src/components/transaction-finish.tsx
  src/components/transaction-sum/transaction-sum.tsx
  src/helpers/calc-fee.ts
  src/i18n.ts
  src/screens/transaction-confirmation.tsx
  src/screens/transaction-sum.tsx
  src/services/eth-network.ts
  src/types.ts
Labels: need-qa

#617 fix(Wallet): show account error
  src/contexts/wallets.ts
Labels: need-qa

#616 refactor(BottomPopupContainer): change duration and fix modals
  src/components/bottom-popups/popup-bottom-container.tsx
  src/components/bottom-sheet.tsx
  src/components/modals/error-account-added.tsx
  src/components/modals/error-create-account.tsx
  src/components/modals/no-internet.tsx
  src/i18n.ts
  src/screens/settings-test.tsx
  src/variables.ts
Labels: need-qa

#621 fix(System): up realm version
  src/models/index.ts
Labels: no-qa

#620 feat(ProviderForm): placeholders
  src/components/settings-provider-edit/settings-provider-edit.tsx
  src/i18n.ts
Labels: need-qa

#618 feat(Home): hide staking and governance on mainnet
  src/screens/home.tsx
Labels: need-qa

#622 fix(Android): dark theme
  android/app/src/main/java/com/haqq/wallet/MainApplication.kt
Labels: need-qa

#623 fix(Settings): fix left icons size
  src/components/ui/menu-navigation-button.tsx
Labels: need-qa

#624 fix(TransactionFinish): fix icon
  android/app/src/main/assets/custom/islm_icon.png
  android/app/src/main/assets/custom/islm_icon@2x.png
  android/app/src/main/assets/custom/islm_icon@3x.png
  android/link-assets-manifest.json
  assets/images/islm_icon.png
  assets/images/islm_icon@2x.png
  assets/images/islm_icon@3x.png
  ios/haqq.xcodeproj/project.pbxproj
  ios/link-assets-manifest.json
  src/components/transaction-finish.tsx
Labels: need-qa

#626 refactor(TextInput): change behaviour
  src/components/settings-address-book.tsx
  src/components/settings-provider-edit/settings-provider-edit.tsx
  src/components/settings-provider-edit/wrapped-input.tsx
  src/components/singin-restore-wallet/signin-restore-wallet.tsx
  src/components/transaction-address.tsx
  src/components/ui/text-field.tsx
  src/components/ui/text.tsx
Labels: need-qa

#628 feature(RestoreWallet): private key
  src/components/singin-restore-wallet/signin-restore-wallet.tsx
  src/screens/signin-restore-wallet.tsx
Labels: need-qa

#649 fix(TransactionSum): fix send to layout and android cursor
  ios/Podfile.lock
  ios/haqq.xcodeproj/project.pbxproj
  src/components/transaction-sum/transaction-sum.tsx
  src/components/ui/sum-block.tsx
Labels: android, need-qa

#647 fix(header): header size android and title align center, fix shadow
  src/screens/home.tsx
Labels: need-qa

#648 fix(notification): notification modal implementation
  src/components/modals/details-qr.tsx
  src/components/notification-message.tsx
  src/components/notifications.tsx
  src/helpers/modal.ts
Labels: need-qa

#646 fix(restoreWallet): paste text color
  src/components/singin-restore-wallet/signin-restore-wallet.tsx
Labels: need-qa

#645 fix(toast): fix shadows
  src/components/bottom-popups/popup-backup-notification/backup-notification.tsx
  src/components/bottom-popups/popup-notification/notification-popup.tsx
  src/components/bottom-popups/popup-track-activity/popup-track-activity.tsx
  src/components/notification-message.tsx
  src/components/wallet-card.tsx
  src/components/wallet-create.tsx
  src/variables.ts
Labels: need-qa

#643 fix(popups): bottom sheet and popup fix
  src/components/bottom-popups/popup-bottom-container.tsx
  src/components/bottom-sheet.tsx
Labels: need-qa

#654 refactor: cleanup code
  src/components/address-empty.tsx
  src/components/address-header.tsx
  src/components/backup-create/mnemonic-word.tsx
  src/components/backup-verify/empty-cell.tsx
  src/components/backup-verify/filled-cell.tsx
  src/components/bottom-popups/popup-bottom-container.tsx
  src/components/dismiss-popup-button.tsx
  src/components/ledger-accounts/ledger-accounts-empty.tsx
  src/components/ledger-agreement/ledger-agreement.tsx
  src/components/ledger-bluetooth/ledger-bluetooth.tsx
  src/components/ledger-scan/ledger-scan-header.tsx
  src/components/ledger-scan/ledger-scan.tsx
  src/components/ledger-verify/ledger-verify.tsx
  src/components/modals/pin.tsx
  src/components/modals/qr/qr-no-access.tsx
  src/components/modals/qr/qr-top-view.tsx
  src/components/modals/qr/qr.tsx
  src/components/onboarding-biometry/onboarding-biometry.tsx
  src/components/pin/numeric-keyboard.tsx
  src/components/pin/pin.tsx
  src/components/popup-header.tsx
  src/components/settings-test/index.tsx
  src/components/settings-test/settings-test.tsx
  src/components/ui/index.ts
  src/components/ui/sum-block.tsx
  src/components/ui/textarea.tsx
  src/components/wallet-create.tsx
  src/i18n.ts
  src/types.ts
Labels: no-qa

#650 feat(Toast): use native implementation
  android/app/src/main/java/com/haqq/wallet/MainApplication.kt
  android/app/src/main/java/com/haqq/wallet/toast/ToastManager.kt
  android/app/src/main/java/com/haqq/wallet/toast/ToastPackage.kt
  ios/Podfile
  ios/Podfile.lock
  ios/haqq.xcodeproj/project.pbxproj
  ios/services/Theme.swift
  ios/services/Toast/Toast.m
  ios/services/Toast/Toast.swift
  ios/services/Toast/ToastView.swift
  ios/services/variables.swift
  src/app.tsx
  src/components/index.ts
  src/components/modals/details-qr.tsx
  src/components/notifications.tsx
  src/components/settings-account-remove-button.tsx
  src/components/settings-security-pin/settings-security-pin.tsx
  src/components/transaction-detail.tsx
  src/components/ui/copy-button.tsx
  src/helpers/modal.ts
  src/screens/settings-account-detail.tsx
  src/screens/transaction-finish.tsx
  src/services/index.ts
  src/services/toast.ts
Labels: need-qa

#651 docs: architecture
  docs/architecture.md
  docs/images/architecture.png
Labels: no-qa

#657 refactor(Staking): refactor code & fix bugs
  package.json
  src/components/home-staking/home-staking.tsx
  src/components/home-staking/staking-active.tsx
  src/components/settings-provider-edit/settings-provider-edit.tsx
  src/components/staking-delegate-finish/staking-delegate-finish.tsx
  src/components/staking-delegate-form/staking-delegate-form.tsx
  src/components/staking-delegate-preview/staking-delegate-preview.tsx
  src/components/staking-info/staking-info.tsx
  src/components/staking-undelegate-finish/staking-undelegate-finish.tsx
  src/components/staking-undelegate-form/staking-undelegate-form.tsx
  src/components/staking-undelegate-preview/staking-undelegate-preview.tsx
  src/components/staking-validators/validator-row.tsx
  src/components/transaction-finish.tsx
  src/components/transaction-sum/transaction-sum.tsx
  src/components/ui/index.ts
  src/components/ui/info-block-amount.tsx
  src/components/ui/inline.tsx
  src/components/ui/network-fee.tsx
  src/components/ui/text-sum.tsx
  src/events.ts
  src/helpers/staking.ts
  src/hooks/use-sum-amount.ts
  src/hooks/use-throttle.ts
  src/i18n.ts
  src/models/staking-metadata.ts
  src/models/wallet.ts
  src/screens/home-staking.tsx
  src/screens/home.tsx
  src/screens/staking-delegate-finish.tsx
  src/screens/staking-info.tsx
  src/screens/staking-undelegate-finish.tsx
  src/screens/staking-validators.tsx
  src/services/cosmos.ts
  src/utils.ts
  yarn.lock
Labels: need-qa

#661 feat(Staking): add hash button
  src/components/staking-delegate-finish/staking-delegate-finish.tsx
  src/components/staking-delegate-preview/staking-delegate-preview.tsx
  src/components/staking-undelegate-finish/staking-undelegate-finish.tsx
  src/components/ui/icon.tsx
  src/components/ui/inline.tsx
  src/screens/staking-delegate-finish.tsx
  src/screens/staking-undelegate-finish.tsx
Labels: no-qa

#658 feat: run app on m1 process
  ios/haqq/haqq.entitlements
Labels: no-qa

#660 fix(use selector): docs mistake
  docs/code-standard.md
Labels: bug, documentation

#677 fix(button): styles large mistake
  src/components/ui/button.tsx
Labels: bug

#678 fix(address book): click list item
  src/components/settings-address-book.tsx
  src/screens/settings-address-book.tsx
Labels: bug, need-qa

#679 fix(settings about): remove animation cropping
  src/components/settings-about.tsx
Labels: bug, animation

#680 fix(Toast): fix crash and maximum elements
  ios/services/Toast/Toast.swift
Labels: bug, need-qa

#681 feat(SettingsProviderEdit): scrollview input
  package.json
  src/components/settings-provider-edit/settings-provider-edit.tsx
  src/components/settings-provider-edit/wrapped-input.tsx
  src/components/ui/text-field.tsx
  src/i18n.ts
  yarn.lock
Labels: refactor, need-qa

#682 feat(SettingsAbout): center bottom text
  src/components/settings-about.tsx
Labels: markup, need-qa

#683 fix(CosmosService): fix locale string
  src/services/cosmos.ts
Labels: bug, need-qa

#686 fix(SettingsAccountStyle): fix error with segmented select
  src/components/settings-account-style.tsx
  src/components/ui/segmented-control.tsx
  src/models/index.ts
  src/types.ts
Labels: need-qa

#688 refactor(PopupHeader): refactor code
  src/app.tsx
  src/components/index.ts
  src/components/popup-header.tsx
  src/components/settings-account-detail/index.ts
  src/components/settings-account-detail/settings-account-detail.tsx
  src/components/settings-account-detail/settings-account-remove-button.tsx
  src/helpers/screen-options.ts
  src/i18n.ts
Labels: no-qa

#685 fix(DarkTheme): small fixes
  src/components/address-header.tsx
  src/components/address-row.tsx
  src/components/qr-scanner-button.tsx
  src/components/settings-address-book-edit.tsx
  src/components/settings-address-book.tsx
  src/components/settings-provider-edit/settings-provider-edit.tsx
  src/components/ui/button.tsx
  src/variables/common.ts
Labels: need-qa

#687 refactor: tsc types
  package.json
  src/app.tsx
  src/colors.ts
  src/components/actions-sheet/index.android.tsx
  src/components/finish.tsx
  src/components/modals/error-create-account.tsx
  src/components/modals/pin.tsx
  src/components/pin.tsx
  src/components/popup-header.tsx
  src/components/settings-provider-edit/settings-provider-edit.tsx
  src/components/settings-provider-edit/wrapped-input.tsx
  src/components/settings-security-pin/settings-security-pin.tsx
  src/components/settings-security/settings-security.tsx
  src/components/staking-info/block.tsx
  src/components/staking-info/staking-info.tsx
  src/components/ui/text.tsx
  src/models/provider.ts
  src/screens/ledger-finish.tsx
  src/screens/onboarding-finish.tsx
  src/services/push-notifications.ts
  src/types.ts
  yarn.lock
Labels: no-qa

#693 [Snyk] Upgrade @react-navigation/native from 6.0.14 to 6.0.16
  package.json
  yarn.lock
Labels: no-qa

#691 [Snyk] Upgrade @react-native-community/netinfo from 9.3.6 to 9.3.7
  package.json
  yarn.lock
Labels: no-qa

#690 [Snyk] Upgrade realm from 11.2.0 to 11.3.0
  package.json
  yarn.lock
Labels: no-qa

#696 feat(Cosmos): ledger support
  src/components/home-governance/voting-card/voting-card-completed.tsx
  src/components/ledger-accounts/ledger-accounts.tsx
  src/components/ledger-scan/ledger-scan-row.tsx
  src/components/proposal/proposal.tsx
  src/helpers/run-until.ts
  src/models/provider.ts
  src/models/wallet.ts
  src/screens/home-staking.tsx
  src/screens/staking-delegate-preview.tsx
  src/screens/staking-info.tsx
  src/services/cosmos.ts
  src/services/transport-ledger.ts
  src/services/transport.ts
  src/types.ts
Labels: no-qa

#699 fix(TransactionSum): markup
  src/components/transaction-sum/transaction-sum.tsx
Labels: need-qa

#698 refactor(proposal): comment deposit button
  src/components/proposal/proposal.tsx
Labels: flow, need-qa

#707 feat(WalletCard): hide qr icon
  src/components/wallet-card.tsx
Labels: need-qa

#697 refactor: tsc typings
  src/components/home-governance/home-governance.tsx
  src/components/home-screen/label.tsx
  src/components/home-screen/tab-bar-icon.tsx
  src/components/home-screen/title.tsx
  src/components/popup-header.tsx
  src/components/settings-account-edit.tsx
  src/components/settings-contact-edit.tsx
  src/components/settings-provider-edit/settings-provider-edit.tsx
  src/components/ui/badge.tsx
  src/components/ui/custom-header/custom-header.tsx
  src/components/ui/progress-circle.tsx
  src/components/ui/text.tsx
  src/helpers/create-theme.ts
  src/i18n.ts
  src/screens/home.tsx
  src/screens/settings-account-detail.tsx
  src/screens/settings-providers.tsx
  src/types.ts
Labels: no-qa

#705 refactor(Transports): change way
  index.js
  src/components/home-feed.tsx
  src/components/proposal/proposal.tsx
  src/components/transaction-ledger/transaction-ledger.tsx
  src/components/wallet-card.tsx
  src/components/wallets.tsx
  src/contexts/app.ts
  src/contexts/wallets.ts
  src/event-actions/index.ts
  src/event-actions/on-deep-link.ts
  src/event-actions/on-push-subscription-add.ts
  src/event-actions/on-staking-sync.ts
  src/event-actions/on-wallet-create.ts
  src/event-actions/on-wallet-remove.ts
  src/event-actions/on-wallets-balance-check.ts
  src/events.ts
  src/models/index.ts
  src/models/wallet.ts
  src/screens/home-feed.tsx
  src/screens/home-staking.tsx
  src/screens/staking-delegate-preview.tsx
  src/screens/staking-info.tsx
  src/screens/staking-undelegate-preview.tsx
  src/screens/transaction-confirmation.tsx
  src/screens/transaction-ledger.tsx
  src/screens/wallets.tsx
  src/services/cosmos.ts
  src/services/eth-network.ts
  src/services/transport-hot.ts
  src/services/transport-ledger.ts
  src/services/transport-utils.ts
  src/services/transport.ts
  src/types.ts
Labels: need-qa

#711 fix(staking delegate): info block
  src/components/staking-delegate-preview/staking-delegate-preview.tsx
Labels: bug

#712 refactor: tsc typings
  .github/workflows/main.yml
  .gitignore
  hooks/pre-commit
  package.json
  src/components/backup-create/backup-create.tsx
  src/components/backup-warning/backup-warning.tsx
  src/components/home-screen/label.tsx
  src/components/home-screen/title.tsx
  src/components/modals/details-qr.tsx
  src/components/modals/pin.tsx
  src/components/proposal/proposal.tsx
  src/components/settings-provider-edit/settings-provider-edit.tsx
  src/components/staking-delegate-preview/staking-delegate-preview.tsx
  src/components/staking-info/staking-info.tsx
  src/components/staking-undelegate-form/staking-undelegate-form.tsx
  src/components/staking-undelegate-preview/staking-undelegate-preview.tsx
  src/components/ui/badge.tsx
  src/components/ui/button.tsx
  src/components/ui/custom-header/header-button.tsx
  src/components/ui/data-content.tsx
  src/components/ui/data-view.tsx
  src/components/ui/info-block.tsx
  src/components/ui/info-box.tsx
  src/components/ui/inline.tsx
  src/components/ui/labeled-block.tsx
  src/components/ui/tag.tsx
  src/components/ui/text-field.tsx
  src/i18n.ts
  src/screens/home-settings.tsx
  src/screens/ledger-store-wallet.tsx
  src/types.ts
Labels: no-qa

#721 fix(Texts): replacing content
  ios/Podfile.lock
  package.json
  src/components/bottom-sheet.tsx
  src/components/modals/details-qr.tsx
  src/components/modals/qr/qr.tsx
  src/components/modals/wallets-bottom-sheet.tsx
  src/components/restore-password.tsx
  src/components/transaction-detail.tsx
  src/components/transaction-finish.tsx
  src/hooks/use-sum-amount.ts
  src/i18n.ts
  src/screens/backup-create.tsx
  src/screens/backup.tsx
  src/screens/signin.tsx
  src/screens/transaction-finish.tsx
  yarn.lock
Labels: refactor, need-qa

#738 fix(LedgerAccounts): fix add button position
  src/components/bottom-popups/popup-backup-notification/backup-notification.tsx
  src/components/ledger-accounts/ledger-accounts-row.tsx
  src/components/restore-password.tsx
  src/components/settings-address-book-edit.tsx
  src/components/settings-provider-edit/settings-provider-edit.tsx
  src/components/ui/button.tsx
Labels: need-qa

#724 fix(ProviderEdit): fix hint for form
  src/components/settings-provider-edit/settings-provider-edit.tsx
  src/components/settings-provider-edit/wrapped-input.tsx
Labels: need-qa

#736 fix(Validators): fix validator icon
  src/components/staking-validators/validator-row.tsx
Labels: need-qa

#725 fix(SettingsSecurity): fix spaces
  src/components/settings-security/settings-security.tsx
Labels: need-qa

#727 fix(StakingDelegateForm): move block to center
  src/components/staking-delegate-form/staking-delegate-form.tsx
  src/components/staking-undelegate-form/staking-undelegate-form.tsx
  src/components/ui/spacer.tsx
  src/components/ui/sum-block.tsx
Labels: need-qa

#730 fix(HomeStaking): spaces
  src/components/home-staking/home-staking.tsx
Labels: need-qa

#732 fix(StakingInfo): fix website size
  src/components/staking-info/staking-info.tsx
Labels: need-qa

#734 fix(TextField): space
  src/components/ui/text-field.tsx
Labels: need-qa

#745 fix(restore agreement): ToS and fix animation margin
  src/components/restore-agreement/restore-agreement.tsx
  src/components/ui/index.ts
  src/components/ui/terms.tsx
  src/i18n.ts
  src/screens/restore.tsx
Labels: bug, need-qa

#746 fix(wallet card): icon button size
  src/components/wallet-card.tsx
Labels: bug, need-qa

#747 fix(create agreement): fix animation
  src/components/create-agreement/create-agreement.tsx
Labels: bug, animation, need-qa

#743 fix(proposal): sizes and color
  src/components/proposal/proposal.tsx
  src/components/ui/badge.tsx
  src/components/ui/icon.tsx
Labels: bug, need-qa

#742 fix(home governance): empty category
  src/components/home-governance/home-governance.tsx
  src/components/proposal-voting-empty.tsx
  src/i18n.ts
Labels: bug, need-qa

#741 fix(home governance): double line, add shadows
  src/components/home-governance/voting-card/voting-card-active.tsx
  src/components/home-governance/voting-card/voting-card-completed.tsx
Labels: bug, need-qa

#754 refactor: design review
  assets/animations/body-ledger-dark.json
  assets/animations/body-ledger-light.json
  assets/animations/get-reward-dark.json
  assets/animations/stake-dark-0-20.json
  assets/animations/stake-dark-100.json
  assets/animations/stake-dark-20-100.json
  src/components/home-staking/staking-active.tsx
  src/components/ledger-agreement/ledger-agreement.tsx
  src/components/settings-address-book-edit.tsx
  src/components/staking-delegate-form/staking-delegate-form.tsx
  src/components/transaction-address.tsx
  src/components/transaction-sum/transaction-sum.tsx
  src/i18n.ts
Labels: need-qa

#756 feat(keyboard): dismiss keyboard on background hook
  src/components/ui/keyboard-safe-area/index.android.tsx
  src/components/ui/keyboard-safe-area/index.ios.tsx
  src/hooks/index.ts
  src/hooks/use-keyboard-dismiss-in-background.tsx
Labels: bug, need-qa

#748 feat(Staking): fetch unbounding time
  src/components/staking-delegate-preview/staking-delegate-preview.tsx
  src/components/staking-undelegate-form/staking-undelegate-form.tsx
  src/components/staking-undelegate-preview/staking-undelegate-preview.tsx
  src/components/ui/info-block.tsx
  src/i18n.ts
  src/screens/staking-delegate-preview.tsx
  src/screens/staking-undelegate-form.tsx
  src/screens/staking-undelegate-preview.tsx
  src/services/cosmos.ts
  src/types.ts
Labels: need-qa

#760 refactor: change texts
  src/components/modals/hide.tsx
  src/components/settings-about.tsx
  src/i18n.ts
Labels: need-qa

#761 fix(Auth): hide window
  src/contexts/app.ts
Labels: need-qa

#764 fix: change theme
  src/app.tsx
  src/components/modals/pin.tsx
Labels: need-qa

#765 feat(Ledger): multiple accounts
  src/components/ledger-accounts/ledger-accounts-row.tsx
  src/components/ledger-accounts/ledger-accounts.tsx
  src/components/ledger-verify/ledger-verify.tsx
  src/screens/ledger-accounts.tsx
  src/screens/ledger-store-wallet.tsx
  src/screens/ledger-verify.tsx
  src/types.ts
Labels: need-qa

#762 feat(proposal): loading state
  src/components/bottom-popups/popup-proposal-vote/popup-proposal-vote.tsx
  src/components/modals/index.ts
  src/components/modals/proposal-vote.tsx
  src/components/proposal/proposal-vote.tsx
  src/components/proposal/proposal.tsx
  src/i18n.ts
  src/screens/modals.tsx
  src/screens/proposal.tsx
Labels: refactor, need-qa
