Repository haqq-network/haqq-wallet, pull requests merged in 2022-11, with the labels that each got.

#433 Animation changes in swipeable
  ios/Podfile.lock
  src/components/ui/swipeable-button.tsx
Labels: animation

#416 README.md add
  .env.example
  README.md
Labels: documentation

#427 Fix android input
  package.json
  src/components/transaction-address.tsx
  src/components/ui/icon-button.tsx
  src/components/ui/svg-icon.tsx
  src/components/ui/terms.tsx
  src/components/ui/text-field.tsx
  src/i18n.ts
  src/screens/signin-restore-wallet.tsx
  yarn.lock
Labels: bug, animation, refactor

#432 Card pattern on toggle animation and fast change color
  src/screens/settings-account-style.tsx
Labels: animation, refactor

#428 Refactor backup create
  src/components/backup-create/backup-create.tsx
  src/components/backup-create/index.ts
  src/components/backup-create/mnemonic-word.tsx
  src/components/ui/svg-icon.tsx
  src/hooks/index.tsx
  src/hooks/use-typed-route.ts
  src/i18n.ts
  src/screens/backup-create.tsx
Labels: refactor

#442 i18n backup create
  src/components/backup-create/backup-create.tsx
  src/components/ui/info-block.tsx
Labels: refactor

#445 Add links
  README.md
Labels: documentation

#447 Instruction for icons
  docs/how-to-add-icon.md
  docs/images/how-to-add-icon-ios.png
Labels: documentation

#439 Icon sizes refactor
  src/components/home-screen/tab-bar-icon.tsx
  src/components/modals/hide.tsx
  src/components/pin/numeric-keyboard.tsx
  src/components/ui/icon.tsx
  src/components/wallets.tsx
Labels: refactor

#444 update eslint rule
  .eslintrc.js
  patches/eslint-plugin-react-native+4.0.0.patch
  src/app.tsx
  src/components/backup-notification/backup-notification.tsx
  src/components/modals/qr/qr.tsx
  src/components/staking-delegate-form/staking-delegate-form.tsx
  src/components/staking-info/markdown.tsx
  src/components/ui/button.tsx
  src/components/ui/info-block.tsx
  src/components/ui/sum-block.tsx
  src/components/wallet-create.tsx
Labels: CI/CD

#441 Notification popup
  assets/animations/notification-popup-dark.json
  assets/animations/notification-popup-light.json
  assets/animations/track-activity.json
  ios/haqq/Images.xcassets/Check.imageset/Check.svg
  ios/haqq/Images.xcassets/Check.imageset/Contents.json
  ios/haqq/Images.xcassets/Lock.imageset/Contents.json
  ios/haqq/Images.xcassets/Lock.imageset/Lock.svg
  src/app.tsx
  src/components/backup-create/backup-create.tsx
  src/components/backup-create/mnemonic-word.tsx
  src/components/bottom-popups/index.ts
  src/components/bottom-popups/popup-backup-notification/backup-notification.tsx
  src/components/bottom-popups/popup-backup-notification/index.tsx
  src/components/bottom-popups/popup-bottom-container.tsx
  src/components/bottom-popups/popup-notification/index.ts
  src/components/bottom-popups/popup-notification/notification-popup.tsx
  src/components/bottom-popups/popup-track-activity/index.ts
  src/components/bottom-popups/popup-track-activity/popup-track-activity.tsx
  src/i18n.ts
  src/screens/popup-backup-notification.tsx
  src/screens/popup-notification.tsx
  src/screens/popup-track-activity.tsx
  src/screens/transaction-finish.tsx
  src/types.ts
  yarn.lock
Labels: animation

#478 docs: architecture
  docs/code-standard.md
Labels: documentation

#480 fix: change place for migration run
  src/app.tsx
  src/contexts/app.ts
Labels: bug

#483 fix: add default value for gas price
  src/contexts/transactions.ts
  src/helpers/capture-exception.ts
  src/models/transaction.ts
Labels: bug

#489 feat: create sum amount hook
  src/components/staking-delegate-form/staking-delegate-form.tsx
  src/components/staking-undelegate-form/staking-undelegate-form.tsx
  src/components/transaction-sum/transaction-sum.tsx
  src/hooks/use-sum-amount.ts
Labels: no-qa
