Repository haqq-network/haqq-wallet, pull requests merged in 2023-01, with the labels that each got.

#744 refactor(Markdown): use safe version of markdown parser
  package.json
  src/components/staking-info/markdown.tsx
  yarn.lock
Labels: no-qa

#753 feat(NumberPrecission): use single number precission and format number to floor
  src/components/home-staking/home-staking.tsx
  src/components/home-staking/staking-active.tsx
  src/components/ledger-accounts/ledger-accounts-row.tsx
  src/components/proposal-deposit-finish/proposal-deposit-finish.tsx
  src/components/proposal-deposit-preview/proposal-deposit-preview.tsx
  src/components/staking-delegate-finish/staking-delegate-finish.tsx
  src/components/staking-delegate-preview/staking-delegate-preview.tsx
  src/components/staking-info/staking-info.tsx
  src/components/staking-undelegate-finish/staking-undelegate-finish.tsx
  src/components/staking-undelegate-preview/staking-undelegate-preview.tsx
  src/components/staking-validators/validator-row.tsx
  src/components/transaction-finish.tsx
  src/components/ui/network-fee.tsx
  src/components/ui/sum-block.tsx
  src/components/wallet-card.tsx
  src/models/transaction.ts
  src/utils.ts
  src/variables/common.ts
Labels: no-qa

#768 refactor: use realm wallet
  src/components/settings-account-detail.tsx
  src/contexts/wallets.ts
  src/event-actions/on-wallet-create.ts
  src/hooks/use-wallet.ts
  src/models/index.ts
  src/models/wallet.ts
  src/screens/backup-verify.tsx
  src/screens/settings-account-detail.tsx
  src/screens/settings-account-edit.tsx
  src/screens/signin-store-wallet.tsx
  src/screens/signup-store-wallet.tsx
  src/types.ts
Labels: need-qa

#771 feat: ledger popup
  ios/Podfile.lock
  metro.config.js
  package.json
  patches/react-native-gesture-handler+2.8.0.patch
  patches/react-native-reanimated+2.13.0.patch
  src/components/modals/index.ts
  src/components/modals/ledger-attention.tsx
  src/components/restore-agreement/restore-agreement.tsx
  src/components/staking-delegate-finish/staking-delegate-finish.tsx
  src/components/staking-delegate-form/staking-delegate-form.tsx
  src/components/staking-validators/validator-row.tsx
  src/events.ts
  src/helpers/await-for-ledger.ts
  src/i18n.ts
  src/models/wallet.ts
  src/screens/home-staking.tsx
  src/screens/modals.tsx
  src/screens/proposal.tsx
  src/screens/settings-test.tsx
  src/screens/staking-delegate-preview.tsx
  src/screens/staking-info.tsx
  src/screens/staking-undelegate-preview.tsx
  src/services/cosmos.ts
  src/services/eth-network.ts
  src/services/transport-hot.ts
  src/services/transport-ledger.ts
  src/types.ts
  src/variables/common.ts
  yarn.lock
Labels: need-qa

#773 fix: mnemonic to lowercase
  src/screens/signin-restore-wallet.tsx
Labels: no-qa

#770 feat: move encryption into package
  .gitignore
  android/app/src/main/java/com/haqq/wallet/MainApplication.kt
  android/app/src/main/java/com/haqq/wallet/encryption/EncryptionManager.kt
  android/app/src/main/java/com/haqq/wallet/encryption/EncryptionPackage.kt
  ios/Podfile.lock
  ios/haqq.xcodeproj/project.pbxproj
  ios/services/Encryption/Encryption.m
  ios/services/Encryption/Encryption.swift
  metro.config.js
  package.json
  src/env.d.ts
  src/models/wallet.ts
  src/passworder.ts
  src/screens/backup-warning.tsx
  yarn.lock
Labels: need-qa

#777 fix: crash on remove wallet
  src/hooks/use-wallet.ts
  src/screens/settings-account-detail.tsx
Labels: need-qa

#778 fix: check private key length
  src/components/singin-restore-wallet/signin-restore-wallet.tsx
Labels: need-qa

#779 chore: update sentry and add breadcrumbs
  ios/Podfile.lock
  package.json
  src/app.tsx
  yarn.lock
Labels: no-qa

#763 feat(search): add searching with animation into header
  src/components/home-governance/home-governance.tsx
  src/components/ui/custom-header/custom-header.tsx
  src/components/ui/custom-header/search-line.tsx
  src/hooks/use-proposals.ts
  src/i18n.ts
  src/screens/home-governance.tsx
  src/types.ts
Labels: animation, need-qa

#776 feat: use external library
  metro.config.js
  package.json
  src/components/ledger-bluetooth/ledger-bluetooth.tsx
  src/components/ledger-scan/ledger-scan-row.tsx
  src/components/ledger-scan/ledger-scan.tsx
  src/helpers/index.ts
  src/helpers/mockForWallet.ts
  src/helpers/provider-instance.ts
  src/helpers/run-until.ts
  src/hooks/use-wallet.ts
  src/models/wallet.ts
  src/screens/ledger-accounts.tsx
  src/screens/ledger-agreement.tsx
  src/screens/ledger-bluetooth.tsx
  src/screens/ledger-scan.tsx
  src/screens/ledger-verify.tsx
  src/screens/transaction-ledger.tsx
  src/services/transport-ledger.ts
  yarn.lock
Labels: no-qa

#720 flow(mnemonic viewing): view mnemonic phrase in settings and pin guard
  src/app.tsx
  src/components/backup-create/backup-create.tsx
  src/components/backup-create/index.ts
  src/components/home-settings/settings-button.tsx
  src/components/pin-guard/index.ts
  src/components/pin-guard/pin-guard.tsx
  src/components/settings-account-detail.tsx
  src/components/settings-account-detail/settings-account-detail.tsx
  src/components/settings-providers/index.ts
  src/components/settings-security/settings-security.tsx
  src/components/settings-view-recovery-phrase/index.tsx
  src/components/settings-view-recovery-phrase/settings-view-recovery-phrase.tsx
  src/components/ui/index.ts
  src/components/ui/mnemonic-table/index.ts
  src/components/ui/mnemonic-table/mnemonic-table.tsx
  src/components/ui/mnemonic-table/mnemonic-word.tsx
  src/i18n.ts
  src/screens/pin-guard.tsx
  src/screens/settings-account-detail.tsx
  src/screens/settings-providers.tsx
  src/screens/settings-security.tsx
  src/screens/settings-view-recovery-phrase.tsx
  src/types.ts
Labels: flow, refactor, need-qa

#781 feat: validators search
  src/app.tsx
  src/components/staking-validators/staking-validators.tsx
  src/components/ui/custom-header/search-line.tsx
  src/screens/staking-validators.tsx
  src/types.ts
Labels: need-qa

#780 refactor: proposal
  src/models/governance-voting.ts
  src/screens/home.tsx
  src/screens/proposal.tsx
  src/services/cosmos.ts
Labels: no-qa

#782 refactor: remove contacts context
  src/components/restore-password.tsx
  src/contexts/contacts.ts
  src/contexts/index.ts
  src/hocs/with-actions-contact-item.tsx
  src/hooks/index.ts
  src/hooks/use-contacts.ts
  src/models/contact.ts
  src/screens/settings-address-book.tsx
  src/screens/transaction-confirmation.tsx
  src/screens/transaction-sum.tsx
Labels: need-qa

#783 refactor: wallet transport provider
  src/helpers/provider-instance.ts
  src/models/wallet.ts
  src/screens/home-staking.tsx
  src/screens/proposal-deposit-preview.tsx
  src/screens/staking-delegate-preview.tsx
  src/screens/staking-info.tsx
  src/screens/staking-undelegate-preview.tsx
  src/screens/transaction-confirmation.tsx
Labels: no-qa

#784 refactor: use-app && wallets
  src/components/settings-security-pin/settings-security-pin.tsx
  src/components/settings-security/settings-security.tsx
  src/components/transaction-address.tsx
  src/contexts/wallets.ts
  src/screens/modals.tsx
  src/screens/settings-security-pin.tsx
  src/screens/settings-security.tsx
  src/screens/signin-store-wallet.tsx
Labels: no-qa

#785 feat: load more ledger accounts
  src/components/ledger-accounts/ledger-accounts-footer.tsx
  src/components/ledger-accounts/ledger-accounts-row.tsx
  src/components/ledger-accounts/ledger-accounts.tsx
  src/i18n.ts
  src/screens/ledger-accounts.tsx
Labels: need-qa

#788 fix: num precission
  src/components/home-staking/staking-active.tsx
  src/components/home-staking/staking-empty.tsx
  src/components/ledger-accounts/ledger-accounts-row.tsx
  src/components/transactions/receive.tsx
  src/components/transactions/send.tsx
  src/components/ui/info-block-amount.tsx
  src/screens/home-staking.tsx
  src/screens/ledger-store-wallet.tsx
  src/services/transport-utils.ts
  src/utils.ts
  src/variables/common.ts
Labels: no-qa

#789 feat: ledger cant connect
  assets/images/ledger-locked.png
  assets/images/ledger-locked@2x.png
  assets/images/ledger-locked@3x.png
  package.json
  src/components/modals/index.ts
  src/components/modals/ledger-locked.tsx
  src/helpers/await-for-popup-closed.ts
  src/helpers/index.ts
  src/i18n.ts
  src/screens/home-staking.tsx
  src/screens/ledger-accounts.tsx
  src/screens/modals.tsx
  src/screens/settings-test.tsx
  src/screens/staking-delegate-preview.tsx
  src/screens/staking-info.tsx
  src/screens/staking-undelegate-preview.tsx
  src/screens/transaction-ledger.tsx
  yarn.lock
Labels: no-qa

#790 refactor: optimise import paths
  babel.config.js
  src/components/backup-finish/backup-finish.tsx
  src/components/backup-warning/backup-warning.tsx
  src/components/bottom-popups/popup-backup-notification/backup-notification.tsx
  src/components/bottom-popups/popup-notification/notification-popup.tsx
  src/components/bottom-popups/popup-track-activity/popup-track-activity.tsx
  src/components/create-agreement/create-agreement.tsx
  src/components/finish.tsx
  src/components/home-staking/staking-active.tsx
  src/components/ledger-agreement/ledger-agreement.tsx
  src/components/ledger-bluetooth/ledger-bluetooth.tsx
  src/components/ledger-verify/ledger-verify.tsx
  src/components/lottie/waiting.tsx
  src/components/modals/details-qr.tsx
  src/components/modals/ledger-attention.tsx
  src/components/modals/ledger-locked.tsx
  src/components/modals/no-internet.tsx
  src/components/proposal-deposit-finish/proposal-deposit-finish.tsx
  src/components/proposal-deposit-preview/proposal-deposit-preview.tsx
  src/components/restore-agreement/restore-agreement.tsx
  src/components/settings-about.tsx
  src/components/staking-delegate-finish/staking-delegate-finish.tsx
  src/components/staking-delegate-preview/staking-delegate-preview.tsx
  src/components/staking-undelegate-finish/staking-undelegate-finish.tsx
  src/components/transaction-confirmation/transaction-confirmation.tsx
  src/components/transaction-finish.tsx
  src/components/transaction-ledger/transaction-ledger.tsx
  src/components/ui/card-mask.tsx
  src/components/ui/svg-icon.tsx
  src/components/welcome.tsx
  src/models/index.ts
  src/models/migration.ts
  tsconfig.json
Labels: no-qa

#791 fix: android search
  android/app/src/main/res/drawable-hdpi/search.png
  android/app/src/main/res/drawable-mdpi/search.png
  android/app/src/main/res/drawable-xhdpi/search.png
  android/app/src/main/res/drawable-xxhdpi/search.png
  android/app/src/main/res/drawable-xxxhdpi/search.png
  src/components/ui/custom-header/search-line.tsx
Labels: need-qa

#792 feat: simulate tx before sending
  src/services/cosmos.ts
  src/types/cosmos.d.ts
Labels: need-qa

#793 feat: show error for failed transaction
  src/components/modals/transaction-error.tsx
  src/i18n.ts
  src/screens/modals.tsx
  src/screens/staking-delegate-preview.tsx
  src/screens/staking-undelegate-preview.tsx
Labels: no-qa

#794 feat: ensure app is installed
  assets/images/ledger-no-app.png
  assets/images/ledger-no-app@2x.png
  assets/images/ledger-no-app@3x.png
  package.json
  src/components/modals/index.ts
  src/components/modals/ledger-no-app.tsx
  src/i18n.ts
  src/screens/ledger-scan.tsx
  src/screens/modals.tsx
  yarn.lock
Labels: no-qa

#795 feat: no bluetooth popup
  assets/images/bluetooth-powered-off.png
  assets/images/bluetooth-powered-off@2x.png
  assets/images/bluetooth-powered-off@3x.png
  assets/images/bluetooth-unauthorized.png
  assets/images/bluetooth-unauthorized@2x.png
  assets/images/bluetooth-unauthorized@3x.png
  package.json
  src/components/modals/bluetooth-powered-off.tsx
  src/components/modals/bluetooth-unauthorized.tsx
  src/helpers/await-for-bluetooth.ts
  src/i18n.ts
  src/screens/home-staking.tsx
  src/screens/modals.tsx
  src/screens/staking-delegate-preview.tsx
  src/screens/staking-info.tsx
  src/screens/staking-undelegate-preview.tsx
  src/screens/transaction-ledger.tsx
  yarn.lock
Labels: no-qa

#799 refactor: create wallet card
  src/components/wallet-create.tsx
  src/components/wallets.tsx
  src/helpers/modal.ts
  src/screens/ledger-store-wallet.tsx
  src/screens/signin-store-wallet.tsx
  src/screens/signup-store-wallet.tsx
  src/screens/wallets.tsx
Labels: no-qa

#805 fix: max card height
  src/components/ui/card.tsx
  src/variables/common.ts
Labels: no-qa

#807 refactor: transactions logic
  src/app.tsx
  src/components/restore-password.tsx
  src/contexts/transactions.ts
  src/contexts/wallets.ts
  src/event-actions/index.ts
  src/event-actions/on-app-started.ts
  src/event-actions/on-deep-link.ts
  src/event-actions/on-push-subscription-add.ts
  src/event-actions/on-transactions-load.ts
  src/event-actions/on-wallet-create.ts
  src/event-actions/on-wallet-remove.ts
  src/event-actions/on-wallet-reset.ts
  src/event-actions/on-wallets-balance-check.ts
  src/events.ts
  src/i18n.ts
  src/models/transaction.ts
  src/models/wallet.ts
  src/screens/home-feed.tsx
  src/screens/signin-store-wallet.tsx
  src/screens/transaction-detail.tsx
  src/screens/transaction-finish.tsx
Labels: need-qa

#801 fix: try to fix ledger bt
  src/screens/ledger-scan.tsx
  src/services/cosmos.ts
Labels: need-qa

#810 fix: vibrate in app
  src/components/modals/pin.tsx
  src/components/ui/sum-block.tsx
  src/screens/settings-address-book.tsx
  src/screens/transaction-sum.tsx
Labels: need-qa

#811 fix: transactions
  src/components/transaction-detail.tsx
  src/helpers/index.ts
  src/helpers/prepare-transactions.ts
  src/hooks/use-sum-amount.ts
  src/models/transaction.ts
  src/screens/home-feed.tsx
  src/screens/transaction-detail.tsx
  src/utils.ts
Labels: no-qa

#813 feat: pin timer
  src/models/user.ts
  src/variables/common.ts
Labels: no-qa

#798 chore(ci): change lables for self hosted build
  .github/workflows/distribute-ios-build.yml
  .github/workflows/distribute.yml
  .github/workflows/patch-build-versions.yml
  ios/Podfile
Labels: no-qa

#800 feat: native sign transaction
  android/app/src/main/java/com/haqq/wallet/ethutils/EthUtilsManager.kt
  android/app/src/main/java/com/haqq/wallet/services/Wallet.kt
  ios/Podfile.lock
  ios/haqq.xcodeproj/project.pbxproj
  ios/services/EthUtils/EthUtils.m
  ios/services/EthUtils/EthUtils.swift
  ios/services/Mnemonic.swift
  ios/services/MnemonicWordlist.swift
  ios/services/Wallet.swift
  ios/services/secp256k1.swift
  metro.config.js
  package.json
  src/contexts/wallets.ts
  src/screens/signin-store-wallet.tsx
  src/screens/signup-store-wallet.tsx
  src/services/eth-utils.ts
  src/services/transport-hot.ts
  yarn.lock
Labels: need-qa
