Repository haqq-network/haqq-wallet, pull requests merged in 2024-03, with the labels that each got.

#1778 feat: android e2e show touches
  .github/workflows/e2e_android.yml
Labels: e2e

#1772 feat: add batched state updates to improve performance
  index.js
  src/hooks/batched-set-state.ts
Labels: e2e

#1777 fix(ImportAccounts): balance fetching fallback to RPC when Indexer.updates got error
  src/components/ledger-accounts/ledger-accounts-row.tsx
  src/helpers/safe-load-balances.ts
  src/screens/DeviceStack/KeystoneStack/keystone-accounts.tsx
  src/screens/DeviceStack/LedgerStack/ledger-accounts.tsx
  src/screens/choose-account-screen.tsx
  src/types.ts
Labels: e2e

#1782 fix: disable unnecessary modal auto close
  src/components/modals/modal-wrapper.tsx
Labels: e2e

#1781 feat: add new test
  e2e/4_settings.test.ts
Labels: e2e

#1783 feat: add "should import mnemonic with duplicated word and see valid phrase in settings" test
  e2e/4_settings.test.ts
Labels: e2e

#1784 fix: remove provider cache
  src/screens/HomeStack/TransactionStack/transaction-confirmation.tsx
Labels: e2e

#1787 fix: transaction address input
  src/components/transaction-address.tsx
Labels: e2e

#1785 fix: android toast
  src/services/toast.ts
Labels: e2e

#1790 chore: update minifyer
  package.json
  yarn.lock
Labels: e2e

#1792 feat: enable dev mode on android e2e emulator
  .github/workflows/e2e_android.yml
Labels: e2e

#1794 fix: 3_routine.test wait for input focus
  e2e/3_routine.test.ts
  e2e/7_coin_delegation.test.ts
Labels: e2e

#1795 fix: transaction ENS issue
  src/screens/HomeStack/TransactionStack/transaction-confirmation.tsx
  src/screens/HomeStack/TransactionStack/transaction-ledger.tsx
  src/services/eth-network.ts
Labels: e2e

#1604 fix(HQM-248): Circular dependencies
  src/contexts/app.ts
  src/event-actions/on-wallets-balance-check.ts
  src/hooks/use-wallets-balance.ts
  src/services/balance.ts
Labels: e2e

#1799 fix: wallet providers cache and error handling
  package.json
  src/helpers/provider-instance.ts
  yarn.lock
Labels: e2e

#1802 feat: update version github action
  .envrc
  .github/workflows/distribute-android.yml
  .github/workflows/distribute-ios.yml
  .github/workflows/distribute.yml
  .github/workflows/e2e_android.yml
  .github/workflows/merged-action.yml
  .github/workflows/review-latest.yml
  .github/workflows/update-version.yml
  .gitignore
  Gemfile.lock
  android/app/build.gradle
  android/app/proguard-rules.pro
  babel.config.js
  e2e/7_coin_delegation.test.ts
  fastlane/Fastfile
  index.js
  ios/Config.xcconfig
  ios/Podfile.lock
  ios/haqq.xcodeproj/project.pbxproj
  ios/haqq.xcodeproj/xcshareddata/xcschemes/haqq.xcscheme
  ios/haqq/Info.plist
  jest.config.js
  package.json
  scripts/update-version.mjs
  scripts/verify-env.mjs
  src/app.tsx
  src/components/captcha/captcha.tsx
  src/components/home-feed.tsx
  src/components/lottie/index.tsx
  src/components/modals/cloud-share-not-found.tsx
  src/components/ui/button.tsx
  src/components/ui/card-small.tsx
  src/components/ui/icon-button.tsx
  src/contexts/app.ts
  src/event-actions/on-app-review-request.ts
  src/event-actions/on-banner-gasdrop-create.ts
  src/helpers/get-google-tokens.ts
  src/helpers/get-provider-for-new-wallet.ts
  src/helpers/is-feature-enabled.ts
  src/models/user.ts
  src/network.ts
  src/screens/HomeStack/SettingsStack/settings-test.tsx
  src/screens/HomeStack/SssMigrate/sss-migrate-networks.tsx
  src/screens/HomeStack/SssMigrate/sss-migrate-store.tsx
  src/screens/HomeStack/index.tsx
  src/screens/WelcomeStack/SignInStack/signin-networks.tsx
  src/screens/WelcomeStack/SignInStack/signin-store-wallet.tsx
  src/screens/WelcomeStack/SignUpStack/signup-networks.tsx
  src/screens/WelcomeStack/SignUpStack/signup-pin.tsx
  src/screens/WelcomeStack/index.tsx
  src/screens/sss-store-wallet.tsx
  src/services/airdrop.ts
  src/services/mmkv.ts
  src/services/provider-sss.ts
  src/services/push-notifications.ts
  src/services/wallet-connect.ts
  src/types/env.d.ts
  src/utils.ts
  src/variables/common.ts
  yarn.lock
Labels: e2e, releaseAfterMerge

#1810 feat: testting releaseAfterMerge flag
  scripts/update-version.mjs
Labels: releaseAfterMerge

#1811 fix: fastlane
  fastlane/Fastfile
Labels: releaseAfterMerge

#1814 fix: fastlane
  .github/workflows/distribute.yml
  fastlane/Fastfile
Labels: releaseAfterMerge

#1816 fix: jobs
  .github/workflows/distribute-android.yml
  .github/workflows/distribute-ios.yml
  .github/workflows/distribute.yml
  fastlane/Fastfile
Labels: releaseAfterMerge

#1817 fix: fastlane
  .github/workflows/merged-action.yml
  fastlane/Fastfile
Labels: releaseAfterMerge

#1818 fix: fastlane
  .github/workflows/distribute.yml
  .github/workflows/merged-action.yml
  fastlane/Fastfile
Labels: releaseAfterMerge

#1819 fix: quotes
  .github/workflows/distribute.yml
Labels: releaseAfterMerge

#1821 feat: posthog
  .github/workflows/distribute-android.yml
  .github/workflows/distribute-ios.yml
  .github/workflows/e2e_android.yml
  .github/workflows/e2e_ios.yml
  .github/workflows/generate-release-notes.yml
  ios/Podfile.lock
  package.json
  src/app.tsx
  src/components/news-detail/news-detail.tsx
  src/event-actions/on-banner-claim-airdrop.ts
  src/event-actions/on-banner-gasdrop-create.ts
  src/event-actions/on-dynamic-link.ts
  src/event-actions/on-notifications-topic-subscribe.ts
  src/event-actions/on-notifications-topic-unsubscribe.ts
  src/event-actions/on-push-notification.ts
  src/event-actions/on-track-event.ts
  src/helpers/get-app-info.ts
  src/helpers/get_adjust_adid.ts
  src/helpers/webview-adjust-middleware.ts
  src/jailbreak.tsx
  src/route-types.ts
  src/screens/HomeStack/BackupStack/backup-finish.tsx
  src/screens/HomeStack/BrowserStack/browser-home-page-screen.tsx
  src/screens/HomeStack/GovernanceStack/governance-list.tsx
  src/screens/HomeStack/HomeEarnStack/home-earn.tsx
  src/screens/HomeStack/HomeEarnStack/home-staking.tsx
  src/screens/HomeStack/HomeEarnStack/staking-validators.tsx
  src/screens/HomeStack/HomeFeedStack/create.tsx
  src/screens/HomeStack/HomeNewsStack/home-news.tsx
  src/screens/HomeStack/HomeNewsStack/our-news.tsx
  src/screens/HomeStack/ManageAccountsStack/settings-account-detail.tsx
  src/screens/HomeStack/SettingsStack/home-settings.tsx
  src/screens/HomeStack/SettingsStack/settings-test.tsx
  src/screens/HomeStack/StakingDelegateStack/staking-delegate-preview.tsx
  src/screens/HomeStack/TransactionStack/transaction-confirmation.tsx
  src/screens/HomeStack/TransactionStack/transaction-ledger.tsx
  src/screens/HomeStack/TransactionStack/transaction-nft-confirmation.tsx
  src/screens/WelcomeStack/OnboardingStack/onboarding-finish.tsx
  src/screens/WelcomeStack/SignInStack/index.tsx
  src/screens/WelcomeStack/SignUpStack/index.tsx
  src/screens/home-governance.tsx
  src/screens/news-list.tsx
  src/screens/welcome-news.tsx
  src/services/event-tracker.ts
  src/services/push-notifications.ts
  src/types.ts
  src/types/env.d.ts
  src/widgets/ad-widget/index.tsx
  src/widgets/banner-widget/index.tsx
  yarn.lock
Labels: releaseAfterMerge

#1822 fix: fastlane
  .github/workflows/generate-release-notes.yml
  .github/workflows/review-latest.yml
  .github/workflows/slack-notify.yml
  Gemfile.lock
  fastlane/Fastfile
Labels: releaseAfterMerge

#1828 chore: update firebase
  ios/Podfile.lock
  ios/haqq.xcodeproj/project.pbxproj
  package.json
  yarn.lock
Labels: e2e
